- name: RoboShop Project from MongoDB
  hosts: all
  become: true
  tasKs:
    - name: Install Mongodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: latest

    - name: Update Listen Address
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start MongoDB Service
      ansible.builtin.systemd:
        name: mongod
        state: restarted
        enabled: yes
