- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: latest

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.kr7348202.online -uroot -pRoboShop@1 < /app/schema/{{component}}.sql
