- name: Copy RoboShop Configuration
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Disable Nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable Nodejs
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: latest

- name: App Pre-requisites
  ansible.builtin.import_tasks: app-preq.yml


- name:  Download NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Schema Setup
  ansible.builtin.import_tasks: mongo-schema.yml

- name: Systemd Setup
  ansible.builtin.import_tasks: systemd-setup.yml
