- name: RoboShop Project from Redis
  hosts: all
  become: true
  tasks:
    - name: Install Redis Repo
      ansible.builtin.dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: latest
        disable_gpg_check: true

    - name: Enable Redis Remis
      ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

    - name: Install Redis
      ansible.builtin.dnf:
        name: redis
        state: latest

    - name: Update Listen Address /etc/redis.conf
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Update Listen Address /etc/redis/redis.conf
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start redis Service
      ansible.builtin.systemd:
        name: redis
        state: restarted
        enabled: yes
