- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy RoboShop Configuration
  ansible.builtin.copy:
    src: nginx-roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Clean Old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    name: /usr/share/nginx/html
    state: directory

- name: Download and Extract Application Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Download Exporter
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Create Nginx Prometheus Exporter Directory
  ansible.builtin.file:
    name: /opt/nginx_exporter
    state: directory

- name: Download Nginx Prometheus Exporter
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter
    remote_src: yes