- name: Setup Hostname
  ansible.builtin.shell: set-hostname frontend

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy RoboShop Configuration
  ansible.builtin.copy:
    src: nginx-roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf


- name: Clean Old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    name: /usr/share/nginx/html
    state: directory

- name: Download and Extract Application Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Restart Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes


