- name: Copy Filebeat repo file
  ansible.builtin.template:
    src: elk.repo
    dest: /etc/yum.repos.d/elk.repo



- name: Copy Filebeat Configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml


