- name: Copy elk repo file
  ansible.builtin.template:
    src: elk.repo
    dest: /etc/yum.repos.d/elk.repo

#- name: Install filebeat
#  ansible.builtin.dnf:
#    name: filebeat
#    state: installed