
- name: Copy Mongo Configuration File
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongo Client
  ansible.builtin.dnf:
    name: mongodb-org-shell
    state: latest

- name: Load Schema
  ansible.builtin.shell:  mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', 'docdb.{{env}}.endpoint', region='us-east-1') }}:27017 --sslCAFile global-bundle.pem --username docdbadmin --password roboshop1234 </app/schema/catalogue.js </app/schema/{{component}}.js


